export const SAFE_DURATION_FALLBACK = 100;
export const MIN_AUTOPLAY_INTERVAL = 100;
export const MIN_VISIBLE_SLIDES = 1;

export const MIN_REPEATED_CLICK_DESTINATION_POSITION = 0;
export const MAX_REPEATED_CLICK_DESTINATION_POSITION = 1;
export const MIN_REPEATED_CLICK_SPEED_MULTIPLIER = 1;
