export const DEFAULT_SETTINGS = {
  visibleSlidesNr: 3,
  durationAutoplay: 3000,
  intervalAutoplay: 3000,
  durationStep: 2000,
  durationJump: 800,
  errAltPlaceholder: "Downloading Error",
  isPagePaddingOn: false,
  isContentImg: true,
  isAuto: true,
  isPaginationOn: true,
  isControlsOn: true,
  isInteractive: true,
  isFinite: false,
} as const;
